import Vue from 'vue';

import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon, FontAwesomeLayers, FontAwesomeLayersText } from '@fortawesome/vue-fontawesome';
import {
  faChartLine,
  faQuestionCircle,
  faCodeBranch,
  faRocket,
  faTachometerAlt,
  faSpinner,
  faSearch,
  faArchive,
  faPaperPlane,
  faUpload,
  faTrash,
  faHistory,
  faTv,
  faEye,
  faHdd,
  faHome,
  faGlobe,
  faLaptop,
  faExclamationTriangle,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faUser,
  faKey,
  faImage,
  faCheckCircle,
  faUserCircle,
  faSignOutAlt,
  faCogs,
  faUsersCog,
  faPlus,
  faDownload,
  faUsers,
  faWarehouse,
  faSync,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faChartLine,
  faQuestionCircle,
  faCodeBranch,
  faRocket,
  faTachometerAlt,
  faSpinner,
  faSearch,
  faArchive,
  faPaperPlane,
  faUpload,
  faTrash,
  faHistory,
  faTv,
  faHdd,
  faHome,
  faGlobe,
  faLaptop,
  faExclamationTriangle,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faUser,
  faKey,
  faImage,
  faCheckCircle,
  faUserCircle,
  faSignOutAlt,
  faCogs,
  faUsersCog,
  faPlus,
  faDownload,
  faUsers,
  faWarehouse,
  faSync,
  faEye
);

Vue.component('FontAwesomeIcon', FontAwesomeIcon);
Vue.component('FontAwesomeLayers', FontAwesomeLayers);
Vue.component('FontAwesomeLayersText', FontAwesomeLayersText);
